name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential autoconf automake libtool pkg-config nasm

    - name: configure
      run: ./configure --enable-shared --toolchain=gcov

    - name: Build
      run: make

    - name: Run regression tests
      run: make fate

    - name: Run distcheck
      run: make install
